//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriendsVerifier.Properties.Resource {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FriendsVerifier.Properties.Resource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Add a new friend 的本地化字符串。
        /// </summary>
        internal static string AddCommandDescription {
            get {
                return ResourceManager.GetString("AddCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} is added
        ///URL: {1} 的本地化字符串。
        /// </summary>
        internal static string AddSucceedFormat {
            get {
                return ResourceManager.GetString("AddSucceedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Code 的本地化字符串。
        /// </summary>
        internal static string CodeOption {
            get {
                return ResourceManager.GetString("CodeOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The code to verify 的本地化字符串。
        /// </summary>
        internal static string CodeOptionDescription {
            get {
                return ResourceManager.GetString("CodeOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current language is changed to &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string CurrentLanguageChangedFormat {
            get {
                return ResourceManager.GetString("CurrentLanguageChangedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} is not in the friends list 的本地化字符串。
        /// </summary>
        internal static string FriendNotFoundFormat {
            get {
                return ResourceManager.GetString("FriendNotFoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Code 的本地化字符串。
        /// </summary>
        internal static string LangArgument {
            get {
                return ResourceManager.GetString("LangArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set the language code you want to change 的本地化字符串。
        /// </summary>
        internal static string LangArgumentDescription {
            get {
                return ResourceManager.GetString("LangArgumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change the language of this program 的本地化字符串。
        /// </summary>
        internal static string LangCommandDescription {
            get {
                return ResourceManager.GetString("LangCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        internal static string NameArgument {
            get {
                return ResourceManager.GetString("NameArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The name of the friend 的本地化字符串。
        /// </summary>
        internal static string NameArgumentDescription {
            get {
                return ResourceManager.GetString("NameArgumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output the verify URL 的本地化字符串。
        /// </summary>
        internal static string OutputCommandDescription {
            get {
                return ResourceManager.GetString("OutputCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Passkey 的本地化字符串。
        /// </summary>
        internal static string PasskeyOption {
            get {
                return ResourceManager.GetString("PasskeyOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The passkey of the friend 的本地化字符串。
        /// </summary>
        internal static string PasskeyOptionDescription {
            get {
                return ResourceManager.GetString("PasskeyOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove a friend 的本地化字符串。
        /// </summary>
        internal static string RemoveCommandDescription {
            get {
                return ResourceManager.GetString("RemoveCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} is removed 的本地化字符串。
        /// </summary>
        internal static string RemoveSucceedFormat {
            get {
                return ResourceManager.GetString("RemoveSucceedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verify your friends 的本地化字符串。
        /// </summary>
        internal static string RootCommandDescription {
            get {
                return ResourceManager.GetString("RootCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time 的本地化字符串。
        /// </summary>
        internal static string TimeOption {
            get {
                return ResourceManager.GetString("TimeOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The time when the code generated 的本地化字符串。
        /// </summary>
        internal static string TimeOptionDescription {
            get {
                return ResourceManager.GetString("TimeOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type 的本地化字符串。
        /// </summary>
        internal static string TypeOption {
            get {
                return ResourceManager.GetString("TypeOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type of output. &quot;Url&quot; for URL link, &quot;QRCode&quot; for QR code and &quot;Code&quot; for generate a code 的本地化字符串。
        /// </summary>
        internal static string TypeOptionDescription {
            get {
                return ResourceManager.GetString("TypeOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} is updated
        ///URL: {1} 的本地化字符串。
        /// </summary>
        internal static string UpdateSucceedFormat {
            get {
                return ResourceManager.GetString("UpdateSucceedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verify the friend 的本地化字符串。
        /// </summary>
        internal static string VerifyCommandDescription {
            get {
                return ResourceManager.GetString("VerifyCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Oh no, your code is wrong! 的本地化字符串。
        /// </summary>
        internal static string VerifyFailedFormat {
            get {
                return ResourceManager.GetString("VerifyFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bad, you are not my friend! 的本地化字符串。
        /// </summary>
        internal static string VerifyNotFoundFormat {
            get {
                return ResourceManager.GetString("VerifyNotFoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hello, {0}! 的本地化字符串。
        /// </summary>
        internal static string VerifySucceedFormat {
            get {
                return ResourceManager.GetString("VerifySucceedFormat", resourceCulture);
            }
        }
    }
}
